# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  mysql_port:
    default: 3306
    description: Port for cluster connection
    type: int

  mysql_host:
    description: Host for cluster connection
    type: string

  mysql_user:
    description: User for cluster connection
    type: string

  mysql_password:
    description: Password for cluster connection
    type: string