# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  mysql_port:
    default: 3306
    description: Port for client connection
    type: int
